### ISSUE TITLE
A lot of tabs shows scrollbar and crashes the application

### ISSUE THREAD

**Issue by tkvw** [marmelab/react-admin#1689]
Example app: https://pp0o4x40p0.codesandbox.io/#/posts/13

I just copied the last tab a couple of times and you'll see a scrollbar at the bottom.
What I expected: that the `Tabs` component would be scrollable and the application not to crash. 
I think this is because the Tabs parent width is implicit instead of explicit. 
![2018-03-22_09-51-42](https://user-images.githubusercontent.com/621098/37760426-ec178526-2db6-11e8-9022-28db830a68b9.gif)

**Comment by fzaninotto** [comment]
I believe it's a material-ui bug.

**Comment by tkvw** [comment]
So I believe it's because the clientWidth can't be calculated correctly. This can be fixed by adding `minWidth:0` on the `content` class of the `Layout` component.

**Comment by oliviertassinari** [comment]
@tkvw Would you mind sharing the link to your codesandbox reproducing the issue? I couldn't do better than https://codesandbox.io/s/k3wpror8yv.

**Comment by fzaninotto** [comment]
@tkvw so is it a material-ui bug, or a react-admin bug?

**Comment by tkvw** [comment]
I think react-admin, what I've debugged is that the tabs container needs a fixed width container. Setting `minWidth` accomplishes this.

**Comment by fzaninotto** [comment]
Fixed by #1721

**Comment by MROFerreiro** [comment]
I think is a materia-ui bug however I could fixed it by setting the classes passed to `<TabbedShowLayoutTabs>` with a `{width: 0}`. Defined a styles object like:
```javascript
const styles = {
  tabs: {
    width: 0
  }
}
```
Used with with my Show resource component:
```JSX
export ResourceShow = withStyles(styles)(ResourceShowView);
```
And in my view added that class to `<TabbedShowLayoutTabs>`:
```JSX
import { Show, TabbedShowLayout, TabbedShowLayoutTabs } from 'react-admin'

const ResourceShowView = ({ classes, ...props}) => (
  <Show {...props} >
    <TabbedShowLayout tabs={<TabbedShowLayoutTabs classes={{scrollable: classes.tabs}} scrollable scrollButtons={'on'}/>}>
      {<YourTabs/>}
    </TabbedShowLayout>
  </Show>
)
```
I don't know why this happens, but it worked! 😃

**Comment by Kmaschta** [comment]
I reproduced with the latest versions (v2 + v3) and the bug is still there.
Still, the app doesn't crash.

**Comment by fzaninotto** [comment]
#4538 breaks FormTabs, we have to revert it in #5132. Therefore, we keep this issue open.

**Comment by akku750156** [comment]
@tkvw can you assign me this issue, if anyone is not working on it for now ?

**Comment by djhi** [comment]
No news for some time, closing
