### ISSUE TITLE
Stylesheet class names conflict with production build (issue with JSS minification)

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/react-admin#1782]
We noticed a severe issue when passing our project in production. Our app seems to be empty:

![image](https://user-images.githubusercontent.com/688373/39239547-85f792fa-4881-11e8-97f3-efb5f177857b.png)

Seems, because everything is correctly set up in the DOM:

![image](https://user-images.githubusercontent.com/688373/39239610-b08d156c-4881-11e8-85e9-03d1f6a1879c.png)

The issue seems related to JSS, which has some troubles generating class names. Each time it see a `withStyles`, it increments a counter. Yet, it seems that MaterialUI and `react-admin` uses two distinct counters. Hence, when the classes are minified (removing the component display name), classes are renamed such as:

* MaterialUI: `jss1`, `jss2`, etc.
* React Admin: `jss1`, `jss2`, etc.

This duplication cause the issue mentioned above.

We temporarily fixed it on our project side, using a custom class name generator, using the same counter for every classes.

``` js
const escapeRegex = /([[\].#*$><+~=|^:(),"'`\s])/g;
let classCounter = 0;

// Heavily inspired of Material UI:
// @see https://github.com/mui-org/material-ui/blob/9cf73828e523451de456ba3dbf2ab15f87cf8504/src/styles/createGenerateClassName.js
// The issue with the MUI function is that is create a new index for each
// new `withStyles`, so we handle have to write our own counter
export const generateClassName = (rule, styleSheet) => {
    classCounter += 1;

    if (process.env.NODE_ENV === 'production') {
        return `c${classCounter}`;
    }

    if (styleSheet && styleSheet.options.classNamePrefix) {
        let prefix = styleSheet.options.classNamePrefix;
        // Sanitize the string as will be used to prefix the generated class name.
        prefix = prefix.replace(escapeRegex, '-');

        if (prefix.match(/^Mui/)) {
            return `${prefix}-${rule.key}`;
        }

        return `${prefix}-${rule.key}-${classCounter}`;
    }

    return `${rule.key}-${classCounter}`;
};
```
Then we wrapped our `Admin` component in:

```js
import JssProvider from 'react-jss/lib/JssProvider';

export default () => (
    <JssProvider generateClassName={generateClassName}>
        <Admin />
    </JssProvider>
);
```
Should I open a PR with this hack-ish fix? It looks like a critical issue, as it prevents from deploying react-admin to production. Yet, I'm not convinced by this solution.

**Comment by Kmaschta** [comment]
I can confirm that we had the same issue on our project.

On production, JSS minify class names with a counter: `jss1`, then `jss2`, etc.
The problem is that there is two stylesheets: Material-UI stylesheet (Paper, Button, etc) and the custom theme stylesheet provided by React Admin.

Both are minified in an isolated fashion, so the first class of the MUI stylesheet is `jss1` and the first class of the custom them is `jss1` too, and so on.
This cause a conflict in the class names and can have various and weird effects on prod (like a white page).

The workaround above, that I wrote, is just a trick to keep the counter sync for both stylesheets.
But it would be nice if we'd fix the root cause.

**Comment by in19farkt** [comment]
It happened because `material-ui` is a dependency for `react-admin`, and if you use `material-ui` with another version, that you have two `withStyles` HOC.

I was helped to remove the `material-ui` from my package.json and reinstall `react-admin`.

**Comment by fzaninotto** [comment]
So that's a matter of having a too rigid version dependency on material-ui. Unfortunately, until material-ui release a stable version, react-admin can't depend on a `~` version (even less on a `^` version), because they break BC at least once a week.

So I guess this problem can be fixed now by using exactly the same material-ui version as react-admin in your `package.json`, or waiting for a stable material-ui release (announced for may 17th), after which we can use a more relaxed version constraint.

**Comment by Kmaschta** [comment]
The issue should now be fixed since https://github.com/marmelab/react-admin/commit/fa174b343599948ca5683f7aa3729cc6293dfee4#diff-47fb44765fe40371ceea73ac4cc821c6R6

**Comment by fzaninotto** [comment]
Closing as the issue is normally fixed. Feel free to reopen if you still experience the problem.

**Comment by Kmaschta** [comment]
I re-open the issue since it seems that it isn't fixed yet. See #1927

- React-admin version: 2.0.3
- React version: 16.4.1

```
"@material-ui/core": "~1.2.2",
"@material-ui/icons": "~1.1.0"
```

**Comment by vascofg** [comment]
Fix by downgrading material-ui in my `package.json` to "~1.0.0".
Note: I had to run `npm dedupe` to remove the extra dependency inside `ra-ui-materialui`.

**Comment by fzaninotto** [comment]
This is fixed by #1909, to be released with 2.1.0.

**Comment by fzaninotto** [comment]
2.1.0 is released, this should now be fixed.

**Comment by AkselsLedins** [comment]
@fzaninotto It seems that this issue persist with the 2.1.0 version
![hq_ laptop with mdpi screen](https://user-images.githubusercontent.com/18367406/42211992-2828c760-7eb5-11e8-95d0-a889fea3c13d.png)
![hq2_ laptop with mdpi screen](https://user-images.githubusercontent.com/18367406/42212199-bceb5c00-7eb5-11e8-9574-4f6721cd6516.png)


maybe @Kmaschta or @jpetitcolas can confirm

I'll stick with the @jpetitcolas solution for the moment

**Comment by fzaninotto** [comment]
Did you remove your `yarn.lock` or `composer.lock` file before reinstalling the dependencies?

**Comment by chr15stevens** [comment]
Fixed in 2.2 by upgrading my material ui to match react-admin's:
`        "@material-ui/core": "^1.4.0",
        "@material-ui/icons": "^1.0.0",`

**Comment by edouardmenayde** [comment]
@chr15stevens You actually saved me hours of headache thank you a lot !

**Comment by Kmaschta** [comment]
I opened an issue on the MUI repo for that. Feel free to add some precisions if needed: https://github.com/mui-org/material-ui/issues/12781

**Comment by oliviertassinari** [comment]
From what I can see on the repository, https://github.com/marmelab/react-admin/search?l=JSON&q=material-ui, Material-UI is set as a dependency. Any specific reason for not having it as a peer dependency?

> We temporarily fixed it on our project side, using a custom class name generator, using the same counter for every classes.

@jpetitcolas Using a `JssProvider` component at the root should be enough to solve the problem. Do you really need a custom class name generator?

**Comment by Kmaschta** [comment]
@fzaninotto and @djhi have the answers about the dependency choices.

@oliviertassinari The idea behind the custom `generateClassName` was to have a singleton counter, and was the only solution that worked at the time (several months ago).

**Comment by oliviertassinari** [comment]
> The idea behind the custom generateClassName was to have a singleton counter, and was the only solution that worked at the time (several months ago).

@Kmaschta Ok thank you for the context. ⚠️ It's working client side but doesn't server side. I would love to have a simplified reproduction example to look into that. It's counter-intuitive.

**Comment by irfanDC** [comment]
Hi, Can we use this with rest api's developed in laravel ?

**Comment by djhi** [comment]
@irfanDC You're commenting on a very specific issue here. What are referring to exactly ?

**Comment by irfanDC** [comment]
> @irfanDC You're commenting on a very specific issue here. What are you referring to exactly ?

No issue, Just asking can we integrate react-admin with laravel as restfull api with axios - npm ?

**Comment by Kmaschta** [comment]
Hi @irfanDC , and thanks for your question. Of course, React Admin can work with any sort of API and you can plug any client you need. I can recommend the tutorial for a good start with this framework: https://marmelab.com/react-admin/

That said, as explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md#asking-questions), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

Once you get a response, please continue to hang out on the react-admin channel in Stack Overflow. That way, you can help newcomers and share your expertise!

**Comment by irfanDC** [comment]
Yes I understand, you can close the issue that is actually not, Thanks for quick response

**Comment by remimarsal** [comment]
Hi! Thanks a lot to @fzaninotto for the awesome framework and to @jpetitcolas for his solution with the ``<JssProvider />`` which did fix the broken layout in prod.

However I still have a delta between the dev & prod builds. I'm not quite sure if this is still related to this specific issue.

Here is the dev build:
<img width="529" alt="capture d ecran 2019-01-26 a 18 00 06" src="https://user-images.githubusercontent.com/8236496/51790441-b5799a80-2195-11e9-96a1-2ece04332eb4.png">

Here is the prod build:
<img width="573" alt="capture d ecran 2019-01-26 a 18 00 20" src="https://user-images.githubusercontent.com/8236496/51790450-cde9b500-2195-11e9-88b1-8793408bdd04.png">

This style is missing in prod:
<img width="226" alt="capture d ecran 2019-01-26 a 18 07 34" src="https://user-images.githubusercontent.com/8236496/51790461-ea85ed00-2195-11e9-8b1e-6659eb2f4069.png">

I'm also surprised that a class is defined as ``ra-input-undefined`` even in dev build. By looking at the source of ``<TextInput />``, it seems it should be a string concatenation with the source prop which is definitely provided when calling the component.

Here's the source:
<img width="619" alt="capture d ecran 2019-01-26 a 18 25 46" src="https://user-images.githubusercontent.com/8236496/51790606-ec50b000-2197-11e9-9132-a6266a7fda24.png">

And while I'm on it, how come the record is injected on the DOM here ?
<img width="411" alt="capture d ecran 2019-01-26 a 18 22 09" src="https://user-images.githubusercontent.com/8236496/51790611-f377be00-2197-11e9-873a-31373a11e4f2.png">

Any hint would be greatly appreciated =)

**Comment by straurob** [comment]
I tried your workaround for my application which faces the identical issue. Unfortunately it doesn't seem to have any affect.

Is there anything more I might to take into account?

> We temporarily fixed it on our project side, using a custom class name generator, using the same counter for every classes.
> 
> ```js
> const escapeRegex = /([[\].#*$><+~=|^:(),"'`\s])/g;
> let classCounter = 0;
> 
> // Heavily inspired of Material UI:
> // @see https://github.com/mui-org/material-ui/blob/9cf73828e523451de456ba3dbf2ab15f87cf8504/src/styles/createGenerateClassName.js
> // The issue with the MUI function is that is create a new index for each
> // new `withStyles`, so we handle have to write our own counter
> export const generateClassName = (rule, styleSheet) => {
>     classCounter += 1;
> 
>     if (process.env.NODE_ENV === 'production') {
>         return `c${classCounter}`;
>     }
> 
>     if (styleSheet && styleSheet.options.classNamePrefix) {
>         let prefix = styleSheet.options.classNamePrefix;
>         // Sanitize the string as will be used to prefix the generated class name.
>         prefix = prefix.replace(escapeRegex, '-');
> 
>         if (prefix.match(/^Mui/)) {
>             return `${prefix}-${rule.key}`;
>         }
> 
>         return `${prefix}-${rule.key}-${classCounter}`;
>     }
> 
>     return `${rule.key}-${classCounter}`;
> };
> ```
> 
> Then we wrapped our `Admin` component in:
> 
> ```js
> import JssProvider from 'react-jss/lib/JssProvider';
> 
> export default () => (
>     <JssProvider generateClassName={generateClassName}>
>         <Admin />
>     </JssProvider>
> );
> ```

**Comment by Kmaschta** [comment]
This issue gets old, and the jss API might have changed since then.
The best workaround to date is to sync the material UI versions with React Admin.

**Comment by MaffooBristol** [comment]
Many's mileage will vary, but for me, choosing `@material-ui/styles` over `@mui/styles` fixed the issue.

I don't know why material-ui has to make such a mess of versions and naming conventions and stuff...!
