### ISSUE TITLE
Filters connected actions doesn't work as expected

### ISSUE THREAD

**Issue by Evgeny81** [marmelab/react-admin#3612]
I faced 2 problems with Filters of a List, but I suppose they are linked somehow.

**What you were expecting:**
1. Added filters doesn't replace each other.
2. After new value added to some filter field, pagination per page value doesn't reset to default.

**What happened instead:**
1. When I click button "ADD FILTER" new filter field is added to filters, but it replaces previously added filter. 
2. When I choice not default value of per page and change some filter value, per page value resets to default value of 10. 

**Steps to reproduce:**
1. Click "ADD FILTER" -> Select a possible filter -> It will appear at the filters panel ->  Click "ADD FILTER" -> Select a  possible filter -> The field replaces previously chosen one.
2. Choice 5 or 25 rows per page in the pagination area -> Type some value to any filter field -> Rows per page resets to 10

**Related code:**

https://codesandbox.io/s/mystifying-silence-dvjev

**Environment**

* React-admin version: 3.0.0-alpha.2, 3.0.0-alpha.3
* React version: 16.9.0
* Browser: Chrome

**Comment by djhi** [comment]
Reproduced. Thanks for the report and the sandbox :)

**Comment by fzaninotto** [comment]
Fixed by #3634

**Comment by Evgeny81** [comment]
Unfortunately the second problem still exists, pagination resets to default on filter change.
