### ISSUE TITLE
Pagination resets after filtering

### ISSUE THREAD

**Issue by Evgeny81** [marmelab/react-admin#3703]
**What you were expecting:**
After new value added to some filter field, pagination per page value doesn't reset to default.

**What happened instead:**
When I choose not default value of per page and change some filter value, per page value resets to default value of 10.

**Steps to reproduce:**

1. Choose 5 or 25 rows per page in the pagination area 
2. Type some value to any filter field 
3. Rows per page resets to 10

**Related code:**
https://codesandbox.io/s/mystifying-silence-dvjev

**Environment**

React-admin version: 3.0.0-alpha.4
React version: 16.9.0
Browser: Chrome

**Comment by djhi** [comment]
Thanks for reporting. Reproduced

**Comment by Evgeny81** [comment]
Probably it happens because query handles previous location but not the current one.

**Comment by fxzhukov** [comment]
@Kmaschta, @fzaninotto PR created - take a look, please. Also, please feel free to propose any better solution.

**Comment by fzaninotto** [comment]
Fixed by #3716

**Comment by m4theushw** [comment]
This bug is back. I think that it is related to `FormSpy` calling an old `setFilters`.  See final-form/react-final-form#569

![pagination](https://user-images.githubusercontent.com/42154031/67643643-539eba80-f8f8-11e9-8787-c5c3afd38d4c.gif)

**Comment by fzaninotto** [comment]
Confirmed. I'm reopening the bug.

**Comment by fzaninotto** [comment]
I've found the bug. It's in `FilterForm`:

```jsx
        <Form
            onSubmit={handleFinalFormSubmit}
            initialValues={mergedInitialValuesWithDefaultValues}
            render={formProps => (
                <>
                    <FormSpy
                        subscription={FormSpySubscription}
                        onChange={({ pristine, values }) => {
                            if (pristine) {
                                return;
                            }
                            props && props.setFilters(values);
                        }}
                    />
                    <FilterForm classes={classes} {...formProps} {...rest} />
                </>
            )}
        />
```

When a user adds a filter, the `FormSpy` triggers the *initial* onChange, ignoring any change in `setFilters` - and therefore ignoring any change to the list state. It's due to a bug in `react-final-form` (https://github.com/final-form/react-final-form/issues/569) fixed (in https://github.com/final-form/react-final-form/pull/572) but not yet released. 

Unfortunately, unless we rewrite final-form's `useFormState` ourselves, it's impossible to solve in react-admin. So we'll have to wait for a new release.

**Comment by fzaninotto** [comment]
Fixed by #4000
