### ISSUE TITLE
[v3] RadioButtonGroupInput does not set Mui-Error on error text

### ISSUE THREAD

**Issue by natrim** [marmelab/react-admin#3733]
RadioButtonGroupInput errors are not red (unlike CheckboxGroupInput)

![Sep-25-2019 09-20-16](https://user-images.githubusercontent.com/488136/65578390-02f11600-df76-11e9-93e4-b22238b40435.gif)

repro: https://codesandbox.io/s/simple-wsknw

Step to reproduce:
1) open edit post
2) try to save without setting the RadioButtonGroupInput
3) error is not red

**Comment by djhi** [comment]
Thanks for reporting !

**Comment by fzaninotto** [comment]
Fixed by #3735

**Comment by clonez** [comment]
> Fixed by #3735

Hi is this committed on the latest react-admin package (4.5.1)? I don't seemed to see the changes, the required validation still not red and doesn't have .mui-error

**Comment by fzaninotto** [comment]
This was fixed in 3.0. If you see a regression in 4.x, please open a new issue, following the issue template.
