### ISSUE TITLE
<ReferenceInput>,< ReferenceArrayInput > ,<AutocompleteInput> validate required message not red as same as other input

### ISSUE THREAD

**Issue by MoonSeeing** [marmelab/react-admin#3849]
**What you were expecting:**
when set validate={required()} in  ReferenceInput or ReferenceArrayInput or AutocompleteInput

```
   <ReferenceInput label="Service Provider" source="serviceProviderId" reference="serviceProviders" validate={required()}>
        <AutocompleteInput optionText="name" />
      </ReferenceInput>

   <ReferenceArrayInput
        label="Eligible Services"
        source="eligibleServiceIds"
        reference="services"
        validate={required()}
      >
        <AutocompleteArrayInput optionText="name" />
      </ReferenceArrayInput>

  <AutocompleteInput source="timeZone" choices={timeZoneChoices} validate={required()} />
```
<img width="233" alt="WeChat66eb1017b42fd008a19284b81795df4b" src="https://user-images.githubusercontent.com/19420622/67193903-b1c72b80-f428-11e9-9f58-691f1477e3f2.png">

the validation message display style not a  red color. At the same time ,ReferenceArrayInput and ReferenceInput do not have * after the label. AutocompleteInput have render the *
 
**Environment**

* React-admin version:3.0.0-beta.2

**Comment by djhi** [comment]
Have you updated to the latest beta ?

**Comment by MoonSeeing** [comment]
> Have you updated to the latest beta ?

just Now i update to last beta2.0 ,but failed ,following is the error.
```
./node_modules/ra-core/esm/util/renderWithRedux.js
Module not found: Can't resolve '@testing-library/react' in '/Users/liuzhichao/AnewWork/cowboy-wms/node_modules/ra-core/esm/util'
```
can you please tell me why ? thanks

**Comment by djhi** [comment]
Yes, we just identified this issue. It will be corrected in next beta. In the mean time, you can install those deps yourself.

**Comment by MoonSeeing** [comment]
> Yes, we just identified this issue. It will be corrected in next beta. In the mean time, you can install those deps yourself.

OK ，thank you very much @djhi

**Comment by MoonSeeing** [comment]
> Yes, we just identified this issue. It will be corrected in next beta. In the mean time, you can install those deps yourself.

i have update to beta2.0 now.but the problem is still existing

**Comment by MoonSeeing** [comment]
@djhi  have you reproduce my problem ? under  beta2.0 , the problem is still existing

**Comment by fzaninotto** [comment]
I can't reproduce the problem with the `next` HEAD. 

![image](https://user-images.githubusercontent.com/99944/67270997-06ff4d80-f4ba-11e9-86fe-d60169c2135f.png)

Please provide a CodeSandbox reproducing the problem.

**Comment by MoonSeeing** [comment]
@fzaninotto you should not use SelectInput in the ReferenceInput， i find  maybe is the AutocompleteInput cause the  problem , you can  reproduce under following  steps.
1. checkout to next
2. find file examples/simple/src/comments/CmommentCreate.js
3.  add 
```
    <ReferenceInput
                source="post_id"
                reference="posts"
                allowEmpty
                validate={required()}
                perPage={10000}
            >
                <AutocompleteInput optionText="title" />
            </ReferenceInput>
```
 to Create SimpleForm.
4.make run-simple
**related code**
 ```
    <Create {...props}>
        <SimpleForm redirect={false} defaultValue={defaultValue}>
            <PostReferenceInput
                source="post_id"
                reference="posts"
                allowEmpty
                validate={required()}
                perPage={10000}
            />
            <ReferenceInput
                source="post_id"
                reference="posts"
                allowEmpty
                validate={required()}
                perPage={10000}
            >
                <AutocompleteInput optionText="title" />
            </ReferenceInput>
            <TextInput
                source="author.name"
                validate={minLength(10)}
                fullWidth
            />
            <DateInput source="created_at" />
            <TextInput source="body" fullWidth={true} multiline={true} />
        </SimpleForm>
    </Create>
```

**Comment by fzaninotto** [comment]
Confirmed and reproduced, thanks!

**Comment by MoonSeeing** [comment]
thanks @fzaninotto

**Comment by fzaninotto** [comment]
Fixed by #3857

**Comment by wmwart** [comment]
@fzaninotto, only part of the problem is fixed. No entry `*` `ReferenceArrayInput` and `ReferenceInput` with `AutocompleteInput`. Rather, `*` appears and then disappears: 
![lQJRAD2lPN](https://user-images.githubusercontent.com/28799755/69217297-6024d480-0b7f-11ea-9559-03f110a7d0ae.gif)

**Comment by fzaninotto** [comment]
@wmwart it seems the problem only occurs in AutocompleteInput. Would you mind opening a new issue, with a code snippet allowing to reproduce the bug?

**Comment by wmwart** [comment]
Done
