### ISSUE TITLE
Too many columns can not view all columns

### ISSUE THREAD

**Issue by mingchen** [marmelab/react-admin#434]
In list view, if I define a lot columns need to be shown, if the row length overflow the right of page, some columns can not be viewed and the page also can not support horizontal scroll.
For example, I define 12 columns, however only 10 can be viewed on page, 2 of them are in right of screen and can not be viewed.

**Comment by wadjeroudi** [comment]
You have to configure columns by size using responsive feature :
https://github.com/marmelab/admin-on-rest/blob/master/docs/Theming.md#responsive-utility
https://github.com/marmelab/admin-on-rest/blob/master/docs/Tutorial.md#responsive-list

**Comment by fzaninotto** [comment]
Fixed in #57 (currently only in the `next` branch)

https://github.com/marmelab/admin-on-rest/pull/57/files#diff-8ff019c2b429722635e5d0ce58e2c0e2

**Comment by mingchen** [comment]
It is still reproducible in the latest code.

To reproduce, open following page:

https://marmelab.com/admin-on-rest-demo/#/commands?_k=wi0hso

Then change window size to make it small in width, you will see some part of right table can not be viewed and it can not horizontal scroll.

**Comment by fzaninotto** [comment]
Again, this is fixed on the `next` branch, not yet released.

**Comment by 1corner** [comment]
We still experience this issue in the latest release. I also tested https://marmelab.com/admin-on-rest-demo/#/commands and have the same issue there. Both on iPhone Safari and Chrome but also when resizing on chrome on desktop. The horizontal scroll do not appear so I can not see columns or edit button.

**Comment by data-server** [comment]
@fzaninotto this issue has been fixed? can you give me some link

**Comment by djhi** [comment]
The next branch has been released. However the project is now named `react-admin`:

`npm install react-admin@2.0.0-beta2`.

Be sure to check the upgrade guide in the `next` branch too

**Comment by data-server** [comment]
@djhi has upgraded , but the issue hasn't been fixed

**Comment by fzaninotto** [comment]
Re-fixed by #1497

**Comment by data-server** [comment]
@fzaninotto next branch has fixed this issue, but master isn't fixed yet.

**Comment by fzaninotto** [comment]
Reopening to consider the fix in `master`

**Comment by fzaninotto** [comment]
Moved to [marmelab/admin-on-rest#2](https://github.com/marmelab/admin-on-rest/issues/2).
