### ISSUE TITLE
Deprecated findDOMNode warning in StrictMode

### ISSUE THREAD

**Issue by leonardoarroyo** [marmelab/react-admin#4793]
This issue was already created(#4577). When it was closed, react-transition-group had not yet been updated. There's a new release in react-transition-node which fixed the issue. Can we get that dep updated?

**Comment by fzaninotto** [comment]
Fixed by #4597

**Comment by rlems** [comment]
I still seem to have this issue with react-transition-group 4.3.0 installed.
I think the issue is solved in 4.4.0: https://github.com/reactjs/react-transition-group/releases/tag/v4.4.0
In the `SimpleFormIterator` there'd have to be a nodeRef provided to the `CCSTransition` and `li` component

**Comment by GimpMaster** [comment]
Sorry to comment on a closed issue, but I am still seeing this issue even with react-transition-group version 4.4.1

Here is yarn.lock

```
react-transition-group@^4.4.0, react-transition-group@^4.4.1:
  version "4.4.1"
  resolved "https://registry.yarnpkg.com/react-transition-group/-/react-transition-group-4.4.1.tgz#63868f9325a38ea5ee9535d828327f85773345c9"
  integrity sha512-Djqr7OQ2aPUiYurhPalTrVy9ddmFCCzwhqQmtN+J3+3DzLO209Fdr70QrN8Z3DsglWql6iY1lDWAfpFiBtuKGw==
  dependencies:
    "@babel/runtime" "^7.5.5"
    dom-helpers "^5.0.1"
    loose-envify "^1.4.0"
    prop-types "^15.6.2"
```

Here is the error I'm seeing:

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Transition)
    in Transition (created by ForwardRef(Grow))
    in ForwardRef(Grow) (created by Unstable_TrapFocus)
    in Unstable_TrapFocus (created by ForwardRef(Modal))
    in div (created by ForwardRef(Modal))
    in ForwardRef(Portal) (created by ForwardRef(Modal))
    in ForwardRef(Modal) (created by ForwardRef(Popover))
    in ForwardRef(Popover) (created by WithStyles(ForwardRef(Popover)))
    in WithStyles(ForwardRef(Popover)) (created by ForwardRef(Menu))
    in ForwardRef(Menu) (created by WithStyles(ForwardRef(Menu)))
    in WithStyles(ForwardRef(Menu)) (created by ForwardRef(SelectInput))
    in ForwardRef(SelectInput) (created by ForwardRef(InputBase))
    in div (created by ForwardRef(InputBase))
    in ForwardRef(InputBase) (created by WithStyles(ForwardRef(InputBase)))
    in WithStyles(ForwardRef(InputBase)) (created by ForwardRef(FilledInput))
    in ForwardRef(FilledInput) (created by WithStyles(ForwardRef(FilledInput)))
    in WithStyles(ForwardRef(FilledInput)) (created by ForwardRef(Select))
    in ForwardRef(Select) (created by WithStyles(ForwardRef(Select)))
    in WithStyles(ForwardRef(Select)) (created by ForwardRef(TextField))
    in div (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (created by ForwardRef(TextField))
    in ForwardRef(TextField) (created by WithStyles(ForwardRef(TextField)))
    in WithStyles(ForwardRef(TextField)) (created by ResettableTextField)
    in ResettableTextField (created by SelectInput)
    in SelectInput (at user.edit.tsx:9)
    in ReferenceInputView (created by ReferenceInput)
    in ReferenceInput (at user.edit.tsx:8)
    in div (created by FormInput)
    in FormInput (created by SimpleFormView)
    in div (created by ForwardRef(CardContent))
    in ForwardRef(CardContent) (created by WithStyles(ForwardRef(CardContent)))
    in WithStyles(ForwardRef(CardContent)) (created by CardContentInner)
    in CardContentInner (created by SimpleFormView)
    in form (created by SimpleFormView)
    in SimpleFormView (created by FormView)
    in FormView (created by ReactFinalForm)
    in ReactFinalForm (created by FormWithRedirect)
    in FormWithRedirect (created by SimpleForm)
    in SimpleForm (at user.edit.tsx:7)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Card))
    in ForwardRef(Card) (created by WithStyles(ForwardRef(Card)))
    in WithStyles(ForwardRef(Card)) (created by EditView)
    in div (created by EditView)
    in div (created by EditView)
    in EditView (created by Edit)
    in Edit (at user.edit.tsx:6)
    in UserEdit (created by WithPermissions)
    in WithPermissions (created by Context.Consumer)
    in Route (created by ResourceRoutes)
    in Switch (created by ResourceRoutes)
    in ResourceRoutes (created by Resource)
    in Resource (at App.tsx:31)
    in Route (created by RoutesWithLayout)
    in Switch (created by RoutesWithLayout)
    in RoutesWithLayout (created by Context.Consumer)
    in div (created by Layout)
    in main (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by WithStyles(Layout))
    in WithStyles(Layout) (created by Context.Consumer)
    in withRouter(WithStyles(Layout)) (created by ConnectFunction)
    in ConnectFunction (created by LayoutWithTheme)
    in ThemeProvider (created by LayoutWithTheme)
    in LayoutWithTheme (at Layout.tsx:16)
    in Unknown (created by Context.Consumer)
    in Route (created by CoreAdminRouter)
    in Switch (created by CoreAdminRouter)
    in div (created by CoreAdminRouter)
    in CoreAdminRouter (created by Context.Consumer)
    in Route (created by CoreAdminUI)
    in Switch (created by CoreAdminUI)
    in CoreAdminUI (created by AdminUI)
    in AdminUI (created by Admin)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by ConnectFunction)
    in ConnectFunction (created by CoreAdminContext)
    in TranslationProvider (created by CoreAdminContext)
    in Provider (created by CoreAdminContext)
    in CoreAdminContext (created by AdminContext)
    in AdminContext (created by Admin)
    in Admin (at App.tsx:17)
    in App (at src/index.tsx:9)
    in StrictMode (at src/index.tsx:8)
```

This happens whenever I click on a select input in the style of below...

```
<ReferenceInput source="companyId" reference="company">
				<SelectInput optionText="name" />
			</ReferenceInput>
```

**Comment by alextaymx** [comment]
I'm still having this warning: 

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at Paper (http://localhost:3000/static/js/0.chunk.js:29516:23)
    at WithStyles(ForwardRef(Paper)) (http://localhost:3000/static/js/0.chunk.js:50570:31)
    at Transition (http://localhost:3000/static/js/0.chunk.js:215420:30)
    at Grow (http://localhost:3000/static/js/0.chunk.js:22257:24)
    at Unstable_TrapFocus (http://localhost:3000/static/js/0.chunk.js:41695:24)
    at div
    at Portal (http://localhost:3000/static/js/0.chunk.js:30602:24)
    at Modal (http://localhost:3000/static/js/0.chunk.js:27754:83)
    at Popover (http://localhost:3000/static/js/0.chunk.js:29729:22)
    at WithStyles(ForwardRef(Popover)) (http://localhost:3000/static/js/0.chunk.js:50570:31)
    at Menu (http://localhost:3000/static/js/0.chunk.js:26691:32)
    at WithStyles(ForwardRef(Menu)) (http://localhost:3000/static/js/0.chunk.js:50570:31)
    at div
    at RegionMenu (http://localhost:3000/static/js/main.chunk.js:3355:84)
    at div
    at Toolbar (http://localhost:3000/static/js/0.chunk.js:40589:23)
    at WithStyles(ForwardRef(Toolbar)) (http://localhost:3000/static/js/0.chunk.js:50570:31)
    at header
    at Paper (http://localhost:3000/static/js/0.chunk.js:29516:23)
    at WithStyles(ForwardRef(Paper)) (http://localhost:3000/static/js/0.chunk.js:50570:31)
    at AppBar (http://localhost:3000/static/js/0.chunk.js:11024:23)
    at WithStyles(ForwardRef(AppBar)) (http://localhost:3000/static/js/0.chunk.js:50570:31)
    at Transition (http://localhost:3000/static/js/0.chunk.js:215420:30)
    at Slide (http://localhost:3000/static/js/0.chunk.js:32428:24)
    at HideOnScroll (http://localhost:3000/static/js/0.chunk.js:170220:24)
    at AppBar (http://localhost:3000/static/js/0.chunk.js:169494:24)
    at CustomAppBar (http://localhost:3000/static/js/main.chunk.js:3518:19)
    at div
    at div
    at LayoutWithoutTheme `(http://localhost:3000/static/js/0.chunk.js:170379:24)`
    at WithStyles(LayoutWithoutTheme) (http://localhost:3000/static/js/0.chunk.js:50570:31)
    at withRouter(WithStyles(LayoutWithoutTheme)) (http://localhost:3000/static/js/0.chunk.js:214329:37)
    at Connect(withRouter(WithStyles(LayoutWithoutTheme))) (http://localhost:3000/static/js/0.chunk.js:211230:75)
    at ThemeProvider (http://localhost:3000/static/js/0.chunk.js:49274:24)
    at Layout (http://localhost:3000/static/js/0.chunk.js:170496:26)
    at MyLayout (http://localhost:3000/static/js/main.chunk.js:3691:80)
    at Route (http://localhost:3000/static/js/0.chunk.js:214072:29)
    at Switch (http://localhost:3000/static/js/0.chunk.js:214274:29)
    at div
    at CoreAdminRouter (http://localhost:3000/static/js/0.chunk.js:138254:87)
    at Route (http://localhost:3000/static/js/0.chunk.js:214072:29)
    at Switch (http://localhost:3000/static/js/0.chunk.js:214274:29)
    at CoreAdminUI (http://localhost:3000/static/js/0.chunk.js:138459:15)
    at AdminUI
    at Router (http://localhost:3000/static/js/0.chunk.js:213707:30)
    at ConnectedRouter (http://localhost:3000/static/js/0.chunk.js:75959:7)
    at ConnectedRouterWithContext (http://localhost:3000/static/js/0.chunk.js:76064:25)
    at Connect(ConnectedRouterWithContext) (http://localhost:3000/static/js/0.chunk.js:211230:75)
    at TranslationProvider (http://localhost:3000/static/js/0.chunk.js:145382:28)
    at Provider (http://localhost:3000/static/js/0.chunk.js:210943:20)
    at CoreAdminContext (http://localhost:3000/static/js/0.chunk.js:138023:25)
    at AdminContext
    at Admin (http://localhost:3000/static/js/0.chunk.js:176761:22)
    at ApolloProvider (http://localhost:3000/static/js/0.chunk.js:6197:19)
    at App (http://localhost:3000/static/js/main.chunk.js:183:97)

**Comment by n-sviridenko** [comment]
Same for me
