### ISSUE TITLE
./node_modules/ra-ui-materialui/esm/list/index.js Cannot find file: 'filter.js' does not match the corresponding name on disk: '.\node_modules\ra-ui-materialui\esm\list\Filter.js'.

### ISSUE THREAD

**Issue by LuluYui** [marmelab/react-admin#5139]
**What you were expecting:**
Followed the react-admin tutorial and follow the subtopic "Making Contact With The API Using a Data Provider" to setup the react-admin test-admin app.

It should be working correctly with following all the documentation. 

**What happened instead:**
![image](https://user-images.githubusercontent.com/32322241/89972878-8e0ff300-dc91-11ea-8c85-acde28acda67.png)

The error prompt shows : 
`./node_modules/ra-ui-materialui/esm/list/index.js Cannot find file: 'filter.js' does not match the corresponding name on disk: '.\node_modules\ra-ui-materialui\esm\list\Filter.js'.`

**Steps to reproduce:**
```
yarn create react-app test-admin
cd test-admin/
yarn add react-admin ra-data-json-server prop-types`
yarn start
```

My App.js.

```
// in src/App.js
import * as React from "react";
import { Admin, Resource, ListGuesser } from 'react-admin';
import jsonServerProvider from 'ra-data-json-server';

const dataProvider = jsonServerProvider('https://jsonplaceholder.typicode.com');

const App = () => (
    <Admin dataProvider={dataProvider}>
        <Resource name="users" list={ListGuesser} />
    </Admin>
);

export default App;
```

**Environment**

* React-admin version: 3.8.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.13.1
* Browser: Chrome
* Stack trace (in case of a JS error):

package.json file:
```
{
  "name": "test-admin",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "prop-types": "^15.7.2",
    "ra-data-json-server": "^3.8.0",
    "react": "^16.13.1",
    "react-admin": "^3.8.0",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by shenglong209** [comment]
in /node_modules/ra-ui-materialui/esm/list/index.js
change "filter.js" to "Filter.js" line 25

**Comment by LuluYui** [comment]
Thank you so much !!!

shenglong209 <notifications@github.com> 於 2020年8月12日 週三 下午12:12寫道：

**Comment by djhi** [comment]
Duplicate of #5135 ?

**Comment by shkyung** [comment]
> in /node_modules/ra-ui-materialui/esm/list/index.js
> change "filter.js" to "Filter.js" line 25

thanks for your help I can run the app locally.
but I have a question.
If somebody clone my repo and install and run, can they face this error ???

**Comment by djhi** [comment]
We released a new version which fixes this issue

**Comment by Taro-Naza** [comment]
Still encountering the same issue when I use the Avatar component in @4.11.2
