### ISSUE TITLE
[v4 beta]: `fieldKey` is not functioning

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#7280]
**What you were expecting:**

`fieldKey` prop to be functioning

**What happened instead:**

`fieldKey` prop is not recognized by Typescript and is not functioning.

**Steps to reproduce:**

Just add it in an ArrayField:
![image](https://user-images.githubusercontent.com/7850073/154856040-35087a5e-426c-4ea0-aeb2-6563ee579e4f.png)

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
<ArrayField
                    label="Accepted Product Types"
                    source="acceptedProductTypes"
                    fieldKey="name"
                >
                    <SingleFieldList>
                        <ChipField source="name" />
                    </SingleFieldList>
                </ArrayField>
```

**Other information:**

I did a global search in the `react-admin` code for `fieldKey`. I could not find it anywhere except of the docs.

Is it obsolete? Still, I need to add something there because I get warnings in the console:
![image](https://user-images.githubusercontent.com/7850073/154856142-4fcb4950-a106-426e-814f-13446d4e6579.png)

**Environment**

React-admin version: "react-admin": "^4.0.0-beta.1"
Last version that did not exhibit the issue (if applicable):
React version: "react": "^17.0.2"
Browser:
Stack trace (in case of a JS error):

**Comment by WiXSL** [comment]
Thanks for reporting this. Marking it as a bug

**Comment by djhi** [comment]
This is actually a documentation issue. This prop is not support nor needed anymore

**Comment by fzaninotto** [comment]
Fixed by #7302

**Comment by joobacca** [comment]
@djhi The fieldKey prop does not exist in the interface ArrayFieldProps, but it's still shown in the documentation: [ArrayField](https://marmelab.com/react-admin/ArrayField.html).

Also, in my case, the object does not have an id key and I get the same error @afilp mentioned above , with the following code: 

```jsx
<ArrayField source="name" sortable={false}>
  <SingleFieldList linkType={false}>
    <TextField source="name" />
  </SingleFieldList>
</ArrayField>
```
the name array looks like this:
```javascript
{
  ...otherKeys,
  name: [
    { iso: '', election_id: '', name: '' },
  ],
}
```

How would I avoid the React error?
