### ISSUE TITLE
ReferenceInput with AutocompleteInput flickers on search

### ISSUE THREAD

**Issue by mediafreakch** [marmelab/react-admin#7767]
**What you were expecting:**

When using AutocompleteInput with a ReferenceInput, the options list should not flicker

**What happened instead:**

Options list somehow appears to be filtered on client-side (matches entries containing the search term), which causes flickering when API returns a no-match.

**Steps to reproduce:**

1. Open code sandbox
2. In the preview window, go to Comments list
3. Click on the icon to create a new comment
4. Now click into the first input that says "Post"
5. Enter character "y"

**Related code:**

CodeSandbox: https://codesandbox.io/s/serene-sutherland-46rs3t?file=/src/comments/CommentCreate.tsx

**Other information:**

![4f116c1676cacbc1b981211b5926ef17](https://user-images.githubusercontent.com/777093/171174630-72d49ea7-c028-4ca0-a223-ae5c5dda5be7.gif)

**Environment**

* React-admin version: 4.1.1

**Comment by septentrion-730n** [comment]
The flicker seems to be linked to [optimistic rendering](https://marmelab.com/react-admin/Actions.html#optimistic-rendering-and-undo) underlying react-admin. The flashing "loading..." message does not fit in this context.

**Comment by davidhenley** [comment]
Thank you! Was about to add this.

**Comment by afilp** [comment]
I also believe that this looks like a "bug". Can you please provide a fix for this? Thanks a ,lot.

**Comment by fzaninotto** [comment]
Fixed by #8037

**Comment by tomek3e** [comment]
The issues still persists in react-admin 4.7.1.
**Related code:**
Codesandbox https://codesandbox.io/s/array-reference-input-xrrv94?file=/src/posts/PostCreate.tsx

**Comment by slax57** [comment]
@tomek3e You may be correct, however this issue was mainly about `ReferenceInput` and `AutocompleteInput`, while your sandbox uses `ReferenceArrayInput` and `AutocompleteArrayInput`.
So this sounds like another bug to me. Could you please open a new dedicated issue?
Thanks
